sub2

diff --git a/.github/workflows/hugo.yaml b/.github/workflows/hugo.yaml
--- a/.github/workflows/hugo.yaml
+++ b/.github/workflows/hugo.yaml
@@ -50,7 +50,7 @@ jobs:
       - name: List themes
         run: ls -R themes || echo "Themes folder missing"
       - name: List theme shortcodes
-        run: ls -l themes/congo/layouts/shortcodes/ || echo "Shortcodes folder missing"
+        run: ls -l themes/congo/layouts/_shortcodes/ || echo "Shortcodes folder missing"
       - name: Setup Pages
         id: pages
         uses: actions/configure-pages@v3
